/**
 * Gravitee.io Portal Rest API
 * API dedicated to the devportal part of Gravitee
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@graviteesource.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

import { ErrorResponse } from '../model/errorResponse';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


export interface VerifyApiKeyAvailabilityRequestParams {
    apiKey: string;
}


@Injectable({
  providedIn: 'root'
})
export class KeysService {

    protected basePath = 'http://localhost:8083/portal/environments/DEFAULT';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();
    public encoder: HttpParameterCodec;

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (configuration) {
            this.configuration = configuration;
        }
        if (typeof this.configuration.basePath !== 'string') {
            if (typeof basePath !== 'string') {
                basePath = this.basePath;
            }
            this.configuration.basePath = basePath;
        }
        this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
    }



    /**
     * Check if an API key is available
     * Verify if an API key is available. It is useful for customers who want to provide their custom API key. 
     * @param requestParameters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public verifyApiKeyAvailability(requestParameters: VerifyApiKeyAvailabilityRequestParams, observe?: 'body', reportProgress?: boolean): Observable<boolean>;
    public verifyApiKeyAvailability(requestParameters: VerifyApiKeyAvailabilityRequestParams, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<boolean>>;
    public verifyApiKeyAvailability(requestParameters: VerifyApiKeyAvailabilityRequestParams, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<boolean>>;
    public verifyApiKeyAvailability(requestParameters: VerifyApiKeyAvailabilityRequestParams, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        const apiKey = requestParameters.apiKey;
        if (apiKey === null || apiKey === undefined) {
            throw new Error('Required parameter apiKey was null or undefined when calling verifyApiKeyAvailability.');
        }

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (apiKey !== undefined && apiKey !== null) {
            queryParameters = queryParameters.set('apiKey', <any>apiKey);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.get<boolean>(`${this.configuration.basePath}/keys/verify`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
